#pragma once

#define TEXBackground L"texture\\Background.jpg"
#define TEXCharacter L"texture\\Character.png"
#define TEXEffect L"texture\\Effect.png"
#define TEXEx L"texture\\Ex.png"
#define TEXFighter L"texture\\Fighter.bmp"
#define TEXlink L"texture\\link.png"
#define TEXnoise_01 L"texture\\noise\\noise_01.png"
#define TEXnoise_02 L"texture\\noise\\noise_02.png"
#define TEXnoise_03 L"texture\\noise\\noise_03.jpg"
#define TEXAlphaCircle L"texture\\particle\\AlphaCircle.png"
#define TEXBubbles50px L"texture\\particle\\Bubbles50px.png"
#define TEXBubbles99px L"texture\\particle\\Bubbles99px.png"
#define TEXCartoonSmoke L"texture\\particle\\CartoonSmoke.png"
#define TEXHardCircle L"texture\\particle\\HardCircle.png"
#define TEXHardRain L"texture\\particle\\HardRain.png"
#define TEXray L"texture\\particle\\ray.png"
#define TEXsmokeparticle L"texture\\particle\\smokeparticle.png"
#define TEXSnow50px L"texture\\particle\\Snow50px.png"
#define TEXSparks L"texture\\particle\\Sparks.png"
#define TEXTILE L"texture\\TILE.bmp"
